permuros/bank/urls.py
from django.urls import path

from . import views

app_name = "bank"

urlpatterns = [
    path("", views.transactions, name="transactions"),
]

permuros/draw/urls.py
from django.urls import path

from . import views

app_name = "draw"

urlpatterns = [
    path("", views.AppView.as_view(), name="app"),
    path("open/<int:pk>/", views.OpenView.as_view(), name="open"),
    path("save/", views.SaveView.as_view(), name="save"),
]

permuros/spotify/urls.py
from django.urls import path

from . import views

app_name = "spotify"

urlpatterns = [
    path("", views.Login.as_view(), name="login"),
    path("callback/", views.LoginCallback.as_view(), name="login_callback"),
    path("refresh_token/", views.RefreshToken.as_view(), name="refresh_token"),
    path("tracks/", views.Tracks.as_view(), name="tracks"),
    path("settings/", views.Settings.as_view(), name="settings"),
]

permuros/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import URLPattern, URLResolver, include, path
from django.views.generic import TemplateView

from . import views

urlpatterns: list[URLResolver | URLPattern] = [
    path("admin/", admin.site.urls),
    path(
        r"accounts/",
        login_required(
            TemplateView.as_view(
                template_name="accounts/index.html",
            )
        ),
    ),
    path(r"accounts/", include("django.contrib.auth.urls")),
    path("write/", include("permuros.write.urls", namespace="write")),
    path("draw/", include("permuros.draw.urls", namespace="draw")),
    path("spotify/", include("permuros.spotify.urls", namespace="spotify")),
    path("bank/", include("permuros.bank.urls", namespace="bank")),
    path("", views.home, name="home"),
]

# Serve static files
if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.append(path("__reload__/", include("django_browser_reload.urls")))

templates/base.html
{% load static compress %}<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{% block title %}PermurOS{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  {% compress css %}
  <link rel="stylesheet" href="{% static "reset.css" %}">
  <link rel="stylesheet" href="{% static "site.css" %}">
  {% endcompress %}
  {% block extra_css %}
  {% endblock %}

  {% block extra_head %}
  {% endblock %}
</head>
<body
  class="{% block body_class %}{% endblock %}"
  hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
>

<header id="titlebar">
  {% block titlebar %}
    <label for="sidebar_toggle" class="sidebar_toggle"><div class="icon"></div></label>
    <h1 id="titlebar_title">
      {% block titlebar_title %}PermurOS{% endblock %}
    </h1>
    <a href="/" id="titlebar_close" class="icon"></a>
  {% endblock %}
</header>

<aside id="sidebar">
  {% block sidebar %}
    <header>
      <div id="sidebar_action">
        {% block sidebar_action %}{% endblock %}
      </div>
      <input type="checkbox" id="sidebar_toggle"{% block sidebar_checkbox %}{% endblock %}>
      <label for="sidebar_toggle" class="sidebar_toggle"><div class="icon"></div></label>
    </header>

    <section id="sidebar_content">{% block sidebar_content %}{% endblock %}</section>

  {% endblock %}
</aside>

<main id="content"{% block "extra_main" %}{% endblock %}>
  {% block content_con %}
    {% block content %}
    {% endblock %}
  {% endblock %}
</main>

{% block end_body %}{% endblock %}
  {% compress js %}
  <script src="{% static "vendor/htmx.min.js" async></script>
  <script src="{% static "site.js" %}" async></script>
  {% endcompress %}
  {% block extra_js %}
  {% endblock %}

</body>
</html>

templates/base_public.html
{% extends "base.html" %}

{% block sidebar %}{% endblock %}

{% block content_con %}
<article>
  {% block content %}
  {% endblock %}
</article>
{% endblock %}

templates/error.html
{% extends "base.html" %}

{% block body_class %}home{% endblock %}

{% block content %}
  <div class="dialog">
      <div class="error">
        <h2>A problem occurred</h2>
        <p>{{ error }}</p>
        <p><a href="/">Return to home</a></p>
      </div>
  </div>
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block body_class %}home{% endblock %}

{% block content %}
  <ul class="cards">

    <li>
      <a href="{% url "write:app" %}">
        <div class="icon" style="mask-image: url('/static/icons/apps/write.svg')"></div>
        <p>Write</p>
      </a>
    </li>

    <li>
      <a href="{% url "draw:app" %}">
        <div class="icon" style="mask-image: url('/static/icons/apps/draw.svg')"></div>
        <p>Draw</p>
      </a>
    </li>

    <li>
      <a href="{% url "spotify:login" %}">
        <div class="icon" style="mask-image: url('/static/icons/apps/spotify.svg')"></div>
        <p>Spotify</p>
      </a>
    </li>

    <li>
      <a href="{% url "bank:transactions" %}">
        <div class="icon" style="mask-image: url('/static/icons/apps/bank.svg')"></div>
        <p>Bank</p>
      </a>
    </li>

  </ul>
{% endblock %}

templates/omusic.html
{% extends "base.html" %}


{% block content %}
  <iframe
    src="https://open.spotify.com/embed/playlist/6LZlE9PKoCv7ZiFjpCp8mh?utm_source=generator&theme=0"
    width="100%"
    height="100%"
    frameBorder="0"
    {# allowfullscreen="" #}
    allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"
    loading="lazy"
  ></iframe>

  <style>

  main {
    position: relative;
  }
  .cover {
    position: absolute;
    &.top {
      background-color: #1f1f1f;

      &.left {
        top: 0;
        left: 0;
        width: 20px;
        height: 20px;
      }

      &.right {
        top: 0;
        right: 0;
        width: 100px;
        height: 100px;
      }

      &.playlist-details {
        top: 25px;
        left: 200px;
        height: 150px;
        width: 300px;
      }
      &.more {
        top: 135px;
        right: 75px;
        width: 50px;
        height: 50px;
      }
    }

    &.bottom {
      background-color: #121212;

      &.left,
      &.right {
        bottom: 0;
        width: 20px;
        height: 20px;
      }
      &.left {
        left: 0;
      }
      &.right {
        right: 0;
      }
    }

    &.album-cover {
      top: 0px;
      left: 0px;
      height: 200px;
      width: 200px;
    }
  }
  </style>
  <div class="cover top left"></div>
  <div class="cover top right"></div>
  <div class="cover top x=playlist-details"></div>
  <div class="cover top more"></div>
  <div class="cover bottom left"></div>
  <div class="cover bottom right"></div>

  <div class="cover album-cover"></div>

{% endblock %}